services:
  - type: web
    name: locallink-web
    env: docker
    envVars:
      - key: DB_HOST
        value: locallink-digital-db.c5c8c4wkwd0m.eu-north-1.rds.amazonaws.com
      - key: DB_NAME
        value: ybt_digital
      - key: DB_USER
        value: admin
      - key: DB_PASS
        value: Adarshkudachi
